name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: git pull on remote server # name of your workflow
        uses: actions/checkout@v2 
        run: | 
          sudo git pull
          for container in traefik vaultwarden portainer jellyfin cadvisor
          do
           cd ~/mediaserver_v2.0/containers/$container
           sudo docker compose up -d --force-recreate
          done