name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: home-vm-01 # I have a second runner configured
    steps:
      - name: git pull on remote server
        uses: actions/checkout@v3
      - name: restart remote containers
        run: | 
          cd ~/media-server_v2.0
          git pull
          for container in traefik
          do
           cd ~/media-server_v2.0/containers/$container
           docker compose up -d --force-recreate
          done