name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: git pull on remote server # name of your workflow
        uses: actions/checkout@v2 
    # - name: automated back up of local docker volumes (step to be added later)
      - name: restart remote containers
        run: | 
          cd ~/media-server_v2.0
          git pull
          for container in traefik vaultwarden portainer jellyfin cadvisor
          do
           cd ~/media-server_v2.0/containers/$container
           sudo docker compose up -d --force-recreate
          done